config/routes.rb
Rails.application.routes.draw do
#Añadidopara usuarios
 get 'admin' => 'admin#index'
 controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
 end
 #FinUsuarios

get 'admin/index'

get 'sessions/new'

get 'sessions/create'

get 'sessions/destroy'

resources :users
resources :publicidads
get 'posts/index'
resources :posts
resources :comments
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index'
end

app/models/publicidad.rb
class Publicidad < ApplicationRecord
    
    mount_uploader :image_url, FotoUploader

    validates :title, :description, :image_url, :publi_url, presence: true
   
end

app/controllers/publicidads_controller.rb
class PublicidadsController < ApplicationController
  include CurrentUser
  before_action :set_publicidad, only: [:show, :edit, :update, :destroy]
  skip_before_action :no_autoriza, only: [:index, :show]

  def verifica_user
    @usu =  lambda {usu?}
    @total = lambda {usu_total?}
    @publi = lambda {usu_publi?}
  end

  # GET /publicidads
  # GET /publicidads.json
  def index
    verifica_user
    @publicidads = Publicidad.all

  end

  # GET /publicidads/1
  # GET /publicidads/1.json
  def show
    verifica_user
  end

  # GET /publicidads/new
  def new
    verifica_user
    (usu_total? || usu_publi?) ? @publicidad = Publicidad.new : (redirect_to login_url, notice: "Sin privilegios de publicidad")

  end

  # GET /publicidads/1/edit
  def edit
    verifica_user
    if (usu_total? || usu_publi?)
    else
      (redirect_to login_url, notice: "Sin privilegios de Publicista")
    end
  end

  # POST /publicidads
  # POST /publicidads.json
  def create
    verifica_user
    if (usu_total? || usu_publi?)
      @publicidad = Publicidad.new(publicidad_params)

      respond_to do |format|
        if @publicidad.save
          format.html { redirect_to @publicidad, notice: 'Publicidad was successfully created.' }
          format.json { render :show, status: :created, location: @publicidad }
        else
          format.html { render :new }
          format.json { render json: @publicidad.errors, status: :unprocessable_entity }
        end
      end
    else
      (redirect_to login_url, notice: "Sin privilegios de publicista")
    end
  end

  # PATCH/PUT /publicidads/1
  # PATCH/PUT /publicidads/1.json
  def update
    verifica_user
    if (usu_total? || usu_publi?)
      respond_to do |format|
        if @publicidad.update(publicidad_params)
          format.html { redirect_to @publicidad, notice: 'Publicidad was successfully updated.' }
          format.json { render :show, status: :ok, location: @publicidad }
        else
          format.html { render :edit }
          format.json { render json: @publicidad.errors, status: :unprocessable_entity }
        end
      end
    else
      (redirect_to login_url, notice: "Sin privilegios de publicista")
    end
  end

  # DELETE /publicidads/1
  # DELETE /publicidads/1.json
  def destroy
    verifica_user
    if (usu_total? || usu_publi?)
      @publicidad.destroy
      respond_to do |format|
        format.html { redirect_to publicidads_url, notice: 'Publicidad was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      (redirect_to login_url, notice: "Sin privilegios de publicista")
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publicidad
      @publicidad = Publicidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publicidad_params
      params.require(:publicidad).permit(:title, :description, :image_url, :publi_url)
    end
end

app/helpers/publicidads_helper.rb
module PublicidadsHelper
end

app/views/publicidads/_form.html.erb
<%= form_with(model: publicidad, local: true, :html => {:multipart => true}) do |form| %>
  <% if publicidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publicidad.errors.count, "error") %> prohibited this publicidad from being saved:</h2>

      <ul>
      <% publicidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :publicidad_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :publicidad_description,  'data-provider': :summernote %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.file_field :image_url, id: :publicidad_image_url %>
  </div>

  <div class="field">
    <%= form.label :publi_url %>
    <%= form.text_field :publi_url, id: :publicidad_publi_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publicidads/_publi.html.erb
<% @publicidads.each do |publicidad| %>
<div class="card my-2">
  <%= image_tag(publicidad.image_url, class:"img-fluid")%>
  <div class="card-body">
    <h5 class="card-title"><%= publicidad.title %></h5>
    <p class="card-text"><%= publicidad.description %></p>
    <a href="<%= publicidad.publi_url %>" class="btn btn-primary">Comprar</a>
  </div>

  <% if  @usu.call %>
    <% if (@total.call || @publi.call)  %>
  <p><%= link_to 'Show', publicidad %></p>
  <p><%= link_to 'Edit', edit_publicidad_path(publicidad) %></p>
  <p><%= link_to 'Destroy', publicidad, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/publicidads/edit.html.erb
<h1>Editing Publicidad</h1>

<%= render 'form', publicidad: @publicidad %>

<%= link_to 'Show', @publicidad %> |
<%= link_to 'Back', publicidads_path %>

app/views/publicidads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Publicidad</h1>

<% @publicidads.each do |publicidad| %>
<div class="card my-2" style="width: 25rem;">
  <%= image_tag(publicidad.image_url, class:"img-fluid")%>
  <div class="card-body">
    <h5 class="card-title"><%= publicidad.title %></h5>
    <p class="card-text"><%= publicidad.description %></p>
    <a href="<%= publicidad.publi_url %>" class="btn btn-primary">Comprar</a>
    <% if  @usu.call %>
      <% if (@total.call || @publi.call)  %>
    <p><%= link_to 'Show', publicidad %></p>
    <p><%= link_to 'Edit', edit_publicidad_path(publicidad) %></p>
    <p><%= link_to 'Destroy', publicidad, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  </div>
</div>
      <% end %>
    <% end %>
<% end %>


<br>

<%= link_to 'New Publicidad', new_publicidad_path, class:"btn btn-info" %>

app/views/publicidads/new.html.erb
<h1>New Publicidad</h1>

<%= render 'form', publicidad: @publicidad %>

<%= link_to 'Back', publicidads_path %>

app/views/publicidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @publicidad.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @publicidad.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag(@publicidad.image_url) %>
</p>

<p>
  <strong>Publi url:</strong>
  <%= @publicidad.publi_url %>
</p>
<% if  @usu.call %>
  <% if (@total.call || @publi.call)  %>
<%= link_to 'Edit', edit_publicidad_path(@publicidad) %> |
<%= link_to 'Back', publicidads_path %>
<% end %>
<% end %>