config/routes.rb
Rails.application.routes.draw do
#Añadidopara usuarios
 get 'admin' => 'admin#index'
 controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
 end
 #FinUsuarios

get 'admin/index'

get 'sessions/new'

get 'sessions/create'

get 'sessions/destroy'

resources :users
resources :publicidads
get 'posts/index'
resources :posts
resources :comments
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'posts#index'
end

app/views/layouts/_cabecera.html.erb
<div class="container">
    <nav class="navbar  navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
      <p class="h3">
    <%= image_tag('donkey-icon.png', class:"img-fluid")%>
    El blog de los burros</p>

    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav ml-auto text-center">
      <li class="nav-item">
        <a class="nav-link h4 text-white" href="/">Inicio</a>
      </li>
      <li class="nav-item">
        <a class="nav-link h4 text-white" href="#">Acerca de</a>
      </li>
      <li class="nav-item">
        <a class="nav-link h4 text-white" href="#">Contactar</a>
      </li>
  </ul>
  </div>
    </nav>
</div>

app/views/layouts/_pie.html.erb
  <div class="container my-3 border-top bg-dark text-white py-4">
        <% if session[:user_id] %>
        <%  @user = User.find_by(id: session[:user_id]) %>
          <div class="row">
          <div class="col-12 col-md-6">
            <h5><strong><%= @user.name %></strong>, administrador con privilegios "<%= @user.tipo %>"</h5> <%= button_to 'Logout', logout_path, method: :delete, class:"btn btn-danger" %>
          </div>
          <div class="col-12 col-md-6">
            <ul >
            <% if(@user.tipo=="Total") %>
              <li><%= link_to 'Users', users_path, class:"h5" %></li>
            <% end %>
            <% if(@user.tipo=="Total" || @user.tipo=="Blog") %>
              <li><%= link_to 'Post', posts_path, class:"h5" %></li>
            <% end %>
            <% if(@user.tipo=="Total" || @user.tipo=="Publicidad") %>
              <li><%= link_to 'Publicidad', publicidads_path, class:"h5" %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render ("layouts/cabecera.html")%>
    <div class="container">
      <%= yield %>
    </div>
    <%= render ("layouts/pie.html")%>

  </body>
</html>